import { Inter, Roboto_Mono } from "next/font/google";
import "../styles/globals.css";
import LoaderLayout from "../components/LoaderLayout";
import ClientWrapper from "../components/ClientWrapper";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`} style={{ margin: 0, padding: 0 }}>
       <ClientWrapper><LoaderLayout>{children}</LoaderLayout></ClientWrapper> 
      </body>
    </html>
  );
}



